### ISSUE TITLE
AblyRealtime module renamed to Ably

### ISSUE THREAD

**Issue by ricardopereira** [ably/ably-ios#510]
Initial work: #490 
Release: https://github.com/ably/ably-ios/releases/tag/0.8.7
Test suite: https://travis-ci.org/ably/ably-ios/builds/167025717

**Tasks:**
- [x] Merge in all other PRs before this release so 0.8 is complete, ideally with Reauth but we can do that after
- [x] Create a new release from tag 0.8.7 after this has been merged.
- [x] Update README
- [x] Update CHANGELOG with important notice about the change. 
- [x] Deprecate old Pod so that it points to the new one (Cocoapods supports deprecation in favour of a new one)
- [x] Update all references in documentation
- [x] Include update in our next product update

**Comment by ricardopereira** [comment]
Tested pod `Ably` on older projects that I have:

```
➜  AblyExampleSwift pod install
Analyzing dependencies
Removing AblyRealtime
Downloading dependencies
Installing Ably (0.8.7)
Using SocketRocket (0.5.1)
Using msgpack (0.1.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
```

```
➜  AblyExampleObjc pod install
Analyzing dependencies
Removing AblyRealtime
Downloading dependencies
Installing Ably (0.8.7)
Using SocketRocket (0.5.1)
Using msgpack (0.1.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
```

It's working.

**Comment by ricardopereira** [comment]
```
➜  ably-ios git:(master) pod trunk deprecate AblyRealtime --in-favor-of=Ably
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
```

😒

**Comment by ricardopereira** [comment]
Actually, it worked 😄

https://cocoapods.org/?q=Ably

![screen shot 2016-10-12 at 13 20 22](https://cloud.githubusercontent.com/assets/3541185/19309758/c4f37d64-907e-11e6-9a2e-8ff348c5058b.png)

**Comment by ricardopereira** [comment]
@mattheworiordan Should I handle `Update all references in documentation` as well?
Is https://github.com/ably/docs the repo?
